### PR TITLE
Add a note that the const_generics feature requires a nightly compiler.

### PR DESCRIPTION
**Pull request by nwalfield**

### CODE REVIEW

**Comment by nwalfield** [comment]
See https://github.com/rodrimati1992/tstr_crates/issues/5

**Comment by rodrimati1992** [comment]
`tstr` with only the `"const_generics"` feature enabled doesn't compile in the current nightly compiler, it's there for a future release where `&'static str` const parameters are stabilized.

You could mention that the feature is unusable in this date though, since `&'static str` const parameters aren't stable. Also, that the `"nightly_const_generics"` feature is an alternative that works in the nightly compiler.

**Comment by nwalfield** [comment]
Thanks.  I don't feel I sufficiently understand how these features work to document them.  I'll leave that to you, or feel free to close this MR.  Thanks for working on tstr, and following up with me!

**Comment by rodrimati1992** [comment]
I made [my own PR](https://github.com/rodrimati1992/tstr_crates/pull/7) attempting to clarify what the `"const_generics"` feature is/does, I'll wait for your opinion before merging that PR.

**Comment by nwalfield** [comment]
That's much easier to understand, thanks!

**Pull request closed without merging**
